project:
  type: book

book:
  title: "BU CS699 Datamining Project - Spring 2025"
  author: "Walter Stock and Arfaan Jeddy"
  date: "2/16/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - data_mining_tools.qmd
    - classification_algorithms.qmd
    - data_mining_procedure.qmd
    - preprocessing.qmd
    - data_mining_results.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



